
// AUTOMATICALLY GENERATED BY JOB SCRAPER
// Date: 2026-01-03 07:43:15

export interface JobOffer {
  title: string;
  company: string;
  source: string;
  date_scraped: string;
  url: string;
}

export const scrapedJobs: JobOffer[] = [
  {
    "title": "Hotel Director",
    "company": "Royal Caribbean Group",
    "source": "MaritimeJobs",
    "url": "https://www.maritimejobs.com",
    "date_scraped": "2026-01-03"
  },
  {
    "title": "Executive Chef",
    "company": "Viking Cruises",
    "source": "MaritimeJobs",
    "url": "https://www.maritimejobs.com",
    "date_scraped": "2026-01-03"
  },
  {
    "title": "Guest Relations Manager",
    "company": "Carnival Cruise Line",
    "source": "MaritimeJobs",
    "url": "https://www.maritimejobs.com",
    "date_scraped": "2026-01-03"
  },
  {
    "title": "Cruise Director",
    "company": "Norwegian Cruise Line",
    "source": "MaritimeJobs",
    "url": "https://www.maritimejobs.com",
    "date_scraped": "2026-01-03"
  },
  {
    "title": "Chief Security Officer",
    "company": "MSC Cruises",
    "source": "MaritimeJobs",
    "url": "https://www.maritimejobs.com",
    "date_scraped": "2026-01-03"
  }
];
